/**
 * Seed data for MSW demo mode — matches fake-backend/db.json.
 * Kept as a separate module so it can be tree-shaken in dev builds.
 */

export default {
  apps: [
    { id: 'acme', name: 'Acme Corp' },
    { id: 'globex', name: 'Globex Inc' },
  ],
  users: [
    { id: '1', username: 'jdoe', firstName: 'John', lastName: 'Doe', email: 'john.doe@example.com', age: 32, country: 'US', department: 'engineering', jobTitle: 'senior-frontend', role: 'editor', active: true, bio: 'Frontend engineer with a passion for clean UI.', managerId: 'a13', appId: 'acme' },
    { id: '2', username: 'asmith', firstName: 'Alice', lastName: 'Smith', email: 'alice.smith@example.com', age: 28, country: 'GB', department: 'design', jobTitle: 'ux-designer', role: 'editor', active: true, bio: 'UX designer focused on accessibility.', managerId: null, appId: 'acme' },
    { id: '3', username: 'bmueller', firstName: 'Boris', lastName: 'Mueller', email: 'boris.mueller@example.com', age: 41, country: 'DE', department: 'engineering', jobTitle: 'tech-lead', role: 'admin', active: true, bio: '', managerId: null, appId: 'acme' },
    { id: '5', username: 'cpatel', firstName: 'Chetan', lastName: 'Patel', email: 'chetan.patel@example.com', age: 35, country: 'IN', department: 'engineering', jobTitle: 'backend-engineer', role: 'editor', active: true, bio: 'Backend engineer, Node.js and Go.', managerId: null, appId: 'acme' },
    { id: 'WZQk9HFF1II', username: 'jroger', firstName: 'John', lastName: 'Roger', email: 'john@roger.io', age: 67, country: 'BR', department: 'engineering', jobTitle: 'devops-engineer', role: 'admin', active: true, bio: '', managerId: 'a11', appId: 'acme' },
    { id: 'a6', username: 'lnova', firstName: 'Lena', lastName: 'Nova', email: 'lena.nova@acme.com', age: 29, country: 'PL', department: 'marketing', jobTitle: 'product-manager', role: 'editor', active: true, bio: '', managerId: null, appId: 'acme' },
    { id: 'a7', username: 'mkhan', firstName: 'Mia', lastName: 'Khan', email: 'mia.khan@acme.com', age: 34, country: 'GB', department: 'hr', jobTitle: 'product-manager', role: 'viewer', active: true, bio: '', managerId: null, appId: 'acme' },
    { id: 'a8', username: 'tfischer', firstName: 'Tom', lastName: 'Fischer', email: 'tom.fischer@acme.com', age: 44, country: 'DE', department: 'finance', jobTitle: 'backend-engineer', role: 'viewer', active: false, bio: '', managerId: null, appId: 'acme' },
    { id: 'a9', username: 'slee', firstName: 'Sara', lastName: 'Lee', email: 'sara.lee@acme.com', age: 26, country: 'KR', department: 'design', jobTitle: 'ux-designer', role: 'editor', active: true, bio: '', managerId: 'a7', appId: 'acme' },
    { id: 'a10', username: 'pmartins', firstName: 'Paulo', lastName: 'Martins', email: 'paulo.martins@acme.com', age: 38, country: 'BR', department: 'product', jobTitle: 'product-manager', role: 'editor', active: true, bio: '', managerId: '1', appId: 'acme' },
    { id: 'a11', username: 'aivanova', firstName: 'Anna', lastName: 'Ivanova', email: 'anna.ivanova@acme.com', age: 31, country: 'UA', department: 'engineering', jobTitle: 'qa-engineer', role: 'editor', active: true, bio: '', managerId: 'a12', appId: 'acme' },
    { id: 'a12', username: 'dgray', firstName: 'David', lastName: 'Gray', email: 'david.gray@acme.com', age: 47, country: 'CA', department: 'engineering', jobTitle: 'tech-lead', role: 'admin', active: true, bio: '', managerId: null, appId: 'acme' },
    { id: 'a13', username: 'ychen', firstName: 'Yuki', lastName: 'Chen', email: 'yuki.chen@acme.com', age: 27, country: 'CN', department: 'design', jobTitle: 'junior-frontend', role: 'viewer', active: false, bio: '', managerId: null, appId: 'acme' },
    { id: 'a14', username: 'rvelez', firstName: 'Rosa', lastName: 'Velez', email: 'rosa.velez@acme.com', age: 33, country: 'MX', department: 'hr', jobTitle: 'product-manager', role: 'editor', active: true, bio: '', managerId: 'a13', appId: 'acme' },
    { id: 'a15', username: 'nbrown', firstName: 'Nick', lastName: 'Brown', email: 'nick.brown@acme.com', age: 40, country: 'AU', department: 'finance', jobTitle: 'backend-engineer', role: 'editor', active: true, bio: '', managerId: 'a9', appId: 'acme' },
    { id: 'a16', username: 'kwojcik', firstName: 'Kasia', lastName: 'Wojcik', email: 'kasia.wojcik@acme.com', age: 30, country: 'PL', department: 'marketing', jobTitle: 'product-manager', role: 'viewer', active: true, bio: '', managerId: null, appId: 'acme' },
    { id: 'a17', username: 'jpark', firstName: 'Jae', lastName: 'Park', email: 'jae.park@acme.com', age: 25, country: 'KR', department: 'engineering', jobTitle: 'junior-frontend', role: 'viewer', active: true, bio: '', managerId: 'a13', appId: 'acme' },
    { id: 'a18', username: 'hbaker', firstName: 'Helen', lastName: 'Baker', email: 'helen.baker@acme.com', age: 52, country: 'GB', department: 'product', jobTitle: 'product-manager', role: 'admin', active: true, bio: '', managerId: 'a11', appId: 'acme' },
    { id: 'a19', username: 'fdurand', firstName: 'Felix', lastName: 'Durand', email: 'felix.durand@acme.com', age: 36, country: 'FR', department: 'engineering', jobTitle: 'backend-engineer', role: 'editor', active: false, bio: '', managerId: '1', appId: 'acme' },
    { id: 'a20', username: 'mdavis', firstName: 'Megan', lastName: 'Davis', email: 'megan.davis@acme.com', age: 29, country: 'US', department: 'design', jobTitle: 'ux-designer', role: 'editor', active: true, bio: '', managerId: null, appId: 'acme' },
    { id: 'a21', username: 'oberg', firstName: 'Olaf', lastName: 'Berg', email: 'olaf.berg@acme.com', age: 43, country: 'NL', department: 'finance', jobTitle: 'tech-lead', role: 'editor', active: true, bio: '', managerId: null, appId: 'acme' },
    { id: 'a22', username: 'zzhang', firstName: 'Zhen', lastName: 'Zhang', email: 'zhen.zhang@acme.com', age: 28, country: 'CN', department: 'engineering', jobTitle: 'senior-frontend', role: 'editor', active: true, bio: '', managerId: null, appId: 'acme' },
    { id: 'a23', username: 'crogers', firstName: 'Chris', lastName: 'Rogers', email: 'chris.rogers@acme.com', age: 55, country: 'US', department: 'hr', jobTitle: 'product-manager', role: 'admin', active: true, bio: '', managerId: 'a9', appId: 'acme' },
    { id: 'a24', username: 'ekim', firstName: 'Eunji', lastName: 'Kim', email: 'eunji.kim@acme.com', age: 24, country: 'KR', department: 'design', jobTitle: 'ux-designer', role: 'viewer', active: false, bio: '', managerId: null, appId: 'acme' },
    { id: 'a25', username: 'vmoreau', firstName: 'Victor', lastName: 'Moreau', email: 'victor.moreau@acme.com', age: 39, country: 'FR', department: 'product', jobTitle: 'backend-engineer', role: 'editor', active: true, bio: '', managerId: null, appId: 'acme' },
    { id: 'g1', username: 'hschmidt', firstName: 'Hans', lastName: 'Schmidt', email: 'hans.schmidt@globex.com', age: 38, country: 'DE', department: 'engineering', jobTitle: 'tech-lead', role: 'admin', active: true, bio: 'Engineering lead at Globex.', managerId: 'g11', appId: 'globex' },
    { id: 'g2', username: 'mwatson', firstName: 'Maria', lastName: 'Watson', email: 'maria.watson@globex.com', age: 30, country: 'US', department: 'hr', jobTitle: 'product-manager', role: 'editor', active: true, bio: '', managerId: 'g10', appId: 'globex' },
    { id: 'g3', username: 'tsato', firstName: 'Taro', lastName: 'Sato', email: 'taro.sato@globex.com', age: 26, country: 'JP', department: 'design', jobTitle: 'ux-designer', role: 'viewer', active: false, bio: 'UX intern.', managerId: 'g11', appId: 'globex' },
    { id: 'g4', username: 'eoliver', firstName: 'Emma', lastName: 'Oliver', email: 'emma.oliver@globex.com', age: 44, country: 'GB', department: 'finance', jobTitle: 'backend-engineer', role: 'editor', active: true, bio: '', managerId: null, appId: 'globex' },
    { id: 'g5', username: 'rlopez', firstName: 'Ricardo', lastName: 'Lopez', email: 'ricardo.lopez@globex.com', age: 31, country: 'MX', department: 'product', jobTitle: 'product-manager', role: 'editor', active: true, bio: 'Product lead.', managerId: 'g6', appId: 'globex' },
    { id: 'g6', username: 'anair', firstName: 'Aisha', lastName: 'Nair', email: 'aisha.nair@globex.com', age: 29, country: 'IN', department: 'engineering', jobTitle: 'qa-engineer', role: 'viewer', active: true, bio: '', managerId: 'g11', appId: 'globex' },
    { id: 'g7', username: 'kmuller', firstName: 'Karl', lastName: 'Muller', email: 'karl.muller@globex.com', age: 45, country: 'DE', department: 'finance', jobTitle: 'tech-lead', role: 'editor', active: true, bio: '', managerId: 'g6', appId: 'globex' },
    { id: 'g8', username: 'pchang', firstName: 'Pei', lastName: 'Chang', email: 'pei.chang@globex.com', age: 32, country: 'CN', department: 'design', jobTitle: 'ux-designer', role: 'viewer', active: false, bio: '', managerId: 'g6', appId: 'globex' },
    { id: 'g9', username: 'jtanaka', firstName: 'Jun', lastName: 'Tanaka', email: 'jun.tanaka@globex.com', age: 36, country: 'JP', department: 'product', jobTitle: 'product-manager', role: 'editor', active: true, bio: '', managerId: 'g7', appId: 'globex' },
    { id: 'g10', username: 'lblanc', firstName: 'Louis', lastName: 'Blanc', email: 'louis.blanc@globex.com', age: 41, country: 'FR', department: 'engineering', jobTitle: 'backend-engineer', role: 'editor', active: true, bio: '', managerId: 'g3', appId: 'globex' },
    { id: 'g11', username: 'sreddy', firstName: 'Sita', lastName: 'Reddy', email: 'sita.reddy@globex.com', age: 27, country: 'IN', department: 'hr', jobTitle: 'product-manager', role: 'viewer', active: true, bio: '', managerId: 'g4', appId: 'globex' },
    { id: 'g12', username: 'bwright', firstName: 'Ben', lastName: 'Wright', email: 'ben.wright@globex.com', age: 50, country: 'GB', department: 'engineering', jobTitle: 'senior-frontend', role: 'admin', active: true, bio: '', managerId: 'g10', appId: 'globex' },
  ],
  departments: [
    { id: 'engineering', name: 'Engineering', group: 'Technology', icon: 'data-shell' },
    { id: 'design', name: 'Design', group: 'Technology', icon: 'paint' },
    { id: 'product', name: 'Product', group: 'Business', icon: 'grid' },
    { id: 'marketing', name: 'Marketing', group: 'Business', icon: 'send' },
    { id: 'hr', name: 'Human Resources', group: 'Operations', icon: 'users' },
    { id: 'finance', name: 'Finance', group: 'Operations', icon: 'card' },
  ],
  countries: [
    { id: '5hfObxiwQWY', code: 'AU', name: 'Australia' },
    { id: 'mRs4TrOz6gM', code: 'BR', name: 'Brazil' },
    { id: 'tvVF3tXMFgA', code: 'CA', name: 'Canada' },
    { id: 'Af5Caruy_R8', code: 'CN', name: 'China' },
    { id: 'q_4fYi0ppnU', code: 'DE', name: 'Germany' },
    { id: 'fURUYy51GcA', code: 'FR', name: 'France' },
    { id: 'TkZXhBg_gJs', code: 'GB', name: 'United Kingdom' },
    { id: 'cMKMOO-rYcI', code: 'IN', name: 'India' },
    { id: 'CKO6-Zljw0U', code: 'JP', name: 'Japan' },
    { id: '8YvSUk2ZBcQ', code: 'KR', name: 'South Korea' },
    { id: 'hb69uZvqsw8', code: 'MX', name: 'Mexico' },
    { id: 'aTIF8BGMhPQ', code: 'NL', name: 'Netherlands' },
    { id: 'VjXJNgr68RY', code: 'PL', name: 'Poland' },
    { id: 'V2o1_Lb29jM', code: 'UA', name: 'Ukraine' },
    { id: 'g9mhyBi95OM', code: 'US', name: 'United States' },
  ],
  'job-titles': [
    { id: 'junior-frontend', name: 'Junior Frontend Engineer' },
    { id: 'senior-frontend', name: 'Senior Frontend Engineer' },
    { id: 'backend-engineer', name: 'Backend Engineer' },
    { id: 'tech-lead', name: 'Tech Lead' },
    { id: 'ux-designer', name: 'UX Designer' },
    { id: 'product-manager', name: 'Product Manager' },
    { id: 'devops-engineer', name: 'DevOps Engineer' },
    { id: 'qa-engineer', name: 'QA Engineer' },
  ],
  invitations: [] as { id: string; [k: string]: unknown }[],
  'audit-log': [
    { id: 'al1', appId: 'acme', action: 'create', entityType: 'user', entityId: '1', userName: 'bmueller', timestamp: '2026-03-30T09:55:00Z', details: 'Created user jdoe' },
    { id: 'al2', appId: 'acme', action: 'update', entityType: 'user', entityId: '2', userName: 'bmueller', timestamp: '2026-03-30T09:40:00Z', details: 'Updated role for asmith' },
    { id: 'al3', appId: 'acme', action: 'invite', entityType: 'invitation', entityId: 'inv1', userName: 'jdoe', timestamp: '2026-03-30T08:15:00Z', details: 'Invited dev@example.com as editor' },
    { id: 'al4', appId: 'acme', action: 'delete', entityType: 'user', entityId: '4', userName: 'bmueller', timestamp: '2026-03-29T17:30:00Z', details: 'Deleted user mlopez' },
    { id: 'al5', appId: 'acme', action: 'role_change', entityType: 'user', entityId: '5', userName: 'bmueller', timestamp: '2026-03-29T16:20:00Z', details: 'Changed role of cpatel to admin' },
    { id: 'al6', appId: 'acme', action: 'create', entityType: 'department', entityId: 'engineering', userName: 'bmueller', timestamp: '2026-03-29T14:00:00Z', details: 'Created department Engineering' },
    { id: 'al7', appId: 'acme', action: 'update', entityType: 'user', entityId: '1', userName: 'jdoe', timestamp: '2026-03-29T11:45:00Z', details: 'Updated profile for jdoe' },
    { id: 'al8', appId: 'acme', action: 'invite', entityType: 'invitation', entityId: 'inv2', userName: 'asmith', timestamp: '2026-03-29T10:30:00Z', details: 'Invited qa@example.com as viewer' },
    { id: 'al9', appId: 'acme', action: 'create', entityType: 'user', entityId: 'WZQk9HFF1II', userName: 'bmueller', timestamp: '2026-03-28T15:55:00Z', details: 'Created user jroger' },
    { id: 'al10', appId: 'acme', action: 'role_change', entityType: 'user', entityId: '2', userName: 'bmueller', timestamp: '2026-03-28T14:10:00Z', details: 'Changed role of asmith to editor' },
    { id: 'al26', appId: 'globex', action: 'create', entityType: 'user', entityId: 'g1', userName: 'hschmidt', timestamp: '2026-03-30T09:00:00Z', details: 'Created user hschmidt' },
    { id: 'al27', appId: 'globex', action: 'invite', entityType: 'invitation', entityId: 'ginv1', userName: 'hschmidt', timestamp: '2026-03-29T14:00:00Z', details: 'Invited new@globex.com as viewer' },
    { id: 'al28', appId: 'globex', action: 'update', entityType: 'user', entityId: 'g2', userName: 'hschmidt', timestamp: '2026-03-28T11:00:00Z', details: 'Updated role for mwatson' },
  ],
  'board-positions': [
    { id: 'bp2', userId: '1', x: 1080, y: 180, appId: 'acme' },
    { id: 'JH49JJR2Apg', userId: 'a11', x: 600, y: 180, appId: 'acme' },
    { id: 'd5u87fHFy6c', userId: 'WZQk9HFF1II', x: 480, y: 360, appId: 'acme' },
    { id: 'jyRDtUJJuMY', userId: 'a12', x: 600, y: 0, appId: 'acme' },
    { id: 'Zek-Zu2K4bA', userId: 'a13', x: 1320, y: 0, appId: 'acme' },
    { id: '62dXxO1riEs', userId: 'a15', x: 0, y: 360, appId: 'acme' },
    { id: '6SDHw7v4g5o', userId: 'a9', x: 120, y: 180, appId: 'acme' },
    { id: 'daHyDDPSPOE', userId: 'a7', x: 120, y: 0, appId: 'acme' },
    { id: 'sN3oKsiPpi0', userId: 'a18', x: 720, y: 360, appId: 'acme' },
    { id: 'mPfUaav2Sos', userId: 'a17', x: 1680, y: 180, appId: 'acme' },
    { id: 'BSCbOZKW3ts', userId: 'a14', x: 1440, y: 180, appId: 'acme' },
    { id: 'P7QtQB9EoSA', userId: 'a19', x: 1200, y: 360, appId: 'acme' },
    { id: '3mWF6qZDH4Q', userId: 'a10', x: 960, y: 360, appId: 'acme' },
    { id: '3ljKF4Obdu4', userId: 'a23', x: 240, y: 360, appId: 'acme' },
    { id: 'ulgdOegZDZM', userId: 'g6', x: 960, y: 360, appId: 'globex' },
    { id: 'XS5uB7iPhaE', userId: 'g7', x: 960, y: 540, appId: 'globex' },
    { id: 'H-27x2RLjUw', userId: 'g8', x: 1200, y: 540, appId: 'globex' },
    { id: 'YKrFNfVFuFE', userId: 'g3', x: 360, y: 360, appId: 'globex' },
    { id: '_st_sx69isw', userId: 'g5', x: 720, y: 540, appId: 'globex' },
    { id: 'MyiCA1jIXX0', userId: 'g9', x: 960, y: 720, appId: 'globex' },
    { id: 'PaQqer_Llt0', userId: 'g10', x: 360, y: 540, appId: 'globex' },
    { id: 'wgm96fkb7qk', userId: 'g2', x: 240, y: 720, appId: 'globex' },
    { id: 'fAuf8eCmLcg', userId: 'g12', x: 480, y: 720, appId: 'globex' },
    { id: 'aRAYk4pPLr0', userId: 'g11', x: 600, y: 180, appId: 'globex' },
    { id: 'TvZfDDNysDY', userId: 'g4', x: 600, y: 0, appId: 'globex' },
    { id: 'jZhYf4wlBGQ', userId: 'g1', x: 0, y: 360, appId: 'globex' },
  ],
};
